name: Daily ULTRATHINK Run
  on:
    schedule:
      - cron: '30 11 * * *'  # Runs at 6:30 AM EST
    workflow_dispatch:  # Lets you run it manually too

  jobs:
    run-ultrathink:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4

        - name: Install requirements
          run: pip install -r requirements.txt

        - name: Run ULTRATHINK and Send Email
          env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
            REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
            REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          run: |
            echo "y" | ./run_hybrid.sh
            python3 resend_last_email.py dollarvora@icloud.com
